### ISSUE TITLE
[Sugestão] Repetição de código nas mensagem de status.

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [Flavio-coutinho/Poupamax#2]
Tem algumas linhas de código repetidas.

<img width="674" alt="Screenshot 2022-11-07 at 00 17 29" src="https://user-images.githubusercontent.com/66704496/200200965-5d4d4e10-7ab6-40bb-9ae2-d2bd4134cdbc.png">

Poderias adotar uma melhor pratica.

Por exemplo:

```js
export type HttpResponse<T = any> = {
	statusCode: number;
	data: T;
};

export interface HttpRequest {
	statusCode: number;
  body?: any
}


export const CREATED = (data: any): HttpResponse => ({
	statusCode: 201,
	data,
});

export const OK = (data: any): HttpResponse => ({
	statusCode: 200,
	data,
});

export const ServerError = (error: Error): HttpResponse => ({
	statusCode: 500,
	data: error.stack,
});```

**Comment by Flavio-coutinho** [comment]
Estou a usar o Koajs, mas vou verificar e tentar fazer deste jeito pra ver no que da.

**Comment by Paulo-Lopes-Estevao** [comment]
Sim, acredito que tambem da abstraindo do `ctx`.

**Comment by Paulo-Lopes-Estevao** [comment]
Podes olhar para esses conceitos
Design Pattern - Abstract Factory
https://deviq.com/principles/dont-repeat-yourself
